# The following is a list of all the possible variables that can be used in the
# configuration file.  The values are the default values.
@hostname = https://rpmsgs3cj0.execute-api.us-east-1.amazonaws.com
#@hostname = http://127.0.0.1:5000
@host = {{hostname}}

# Test the health of the API
GET {{host}}/health

###

# Run Task 1
POST {{host}}/run/task1
content-type: application/json

{
    "text": "This is the best day of my life"
}
###

# Get Task ID
GET {{host}}/run/f65d6fb23bfc411992d83c5a650185a3

###